"""initial schema

Revision ID: 1560d57453ab
Revises:
Create Date: 2026-09-16 10:04:30.088665

upgrade() 가 비어 있는 것은 실수가 아니다.
이 리비전을 만들 때 users·documents 등은 이미 init_db() 의 create_all() 로 만들어져
있었고, autogenerate 는 "모델과 DB 의 차이"만 적기 때문에 차이가 없어서 pass 가 나왔다.

그래도 파일을 지우지 않는다. 이후 리비전이 down_revision 으로 매달릴 기준점이 필요해서다.
(4da9dfda9039 의 down_revision 이 이 번호다. 이 파일이 없으면 다음 리비전을 적용할 수 없다)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1560d57453ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
