from __future__ import annotations

# ══════ 여기부터 직접 채운다 ══════

# class AgentError(Exception): ...
# class NotFound(AgentError): ...
# class GuardTripped(AgentError): ...
# class RateLimited(AgentError): ...
# class AuthFailed(AgentError): ...
