from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# ══════ 여기부터 직접 채운다 ══════

# DOC_ID = ...
# class ChatRequest(BaseModel): ...
# class AnswerSource(BaseModel): ...
# class AnswerOut(BaseModel): ...
